// src/Ascii.jsx
import React, { useEffect, useState, useRef } from "react"
import { css } from "@emotion/react"
import { GU, colors, fonts } from "./styles"
import { raf, randChar } from "./utils"

const CHARS = "0123456789ABCDEFGHIJKLMONOPRSTUVWXYZ-_)()><*$%`"

function asciiStep(currentText, text) {
  return (currentText = [...currentText]
    .map((char, index) => (char === text[index] ? char : randChar(CHARS)))
    .join(""))
}

function Ascii({ text = "", updateInterval = 1000 / 60 }) {
  const elRef = useRef()

  useEffect(() => {
    let textCurrent = " ".repeat(text.length)

    const stop = raf(() => {
      textCurrent = asciiStep(textCurrent, text)

      if (elRef.current) {
        elRef.current.textContent = textCurrent
      }

      if (text === textCurrent) {
        stop()
      }
    }, updateInterval)

    return stop
  }, [updateInterval])

  return (
    <span
      ref={elRef}
      css={css`
        margin: 0;
        padding: 0 calc(1em / 3);
        background: ${colors.green};
        color: ${colors.black};
        font-weight: ${colors.bold};
      `}
    >
      {" "}
    </span>
  )
}

export default Ascii

// src/components/ASCII.svelte
<script>
  export { _class as class };

  export let message = "";
  export let interval = 30;

  let _class,
    loop,
    current = "";

  const _random = () => {
    const alphabet = "0123456789ABCDEFGHIJKLMONOPRSTUVWXYZ-_)()><*$%`";

    return alphabet[Math.floor(Math.random() * alphabet.length)];
  };

  const _refresh = () => {
    let stop = true,
      _current = "";

    for (let i = 0; i < message.length; i++) {
      if (current && current[i] === message[i]) {
        _current += current[i];
      } else {
        stop = false;
        _current += _random();
      }
    }

    current = _current;

    if (stop) clearInterval(loop);
  };

  const ascii = () => {
    loop = setInterval(_refresh, interval);

    return {
      destroy() {},
    };
  };
</script>

<style lang="scss">
  p {
    background: $green;
    color: $black;
    font-weight: $bold;
    margin: 0;
    padding: 0 calc(1em / 3);
    width: fit-content;
  }
</style>

<p use:ascii class={_class}>
  {current}
</p>
