// src/components/Square.svelte
<script>
  import { fade } from "svelte/transition";

  export let height = 300;
  export let width = 300;
  export let em = 12;

  let columns,
    lines,
    loop,
    middle,
    current = "";

  $: {
    lines = Math.floor((height * 1.6632) / em);
    columns = Math.ceil(width / em);
    middle = Math.ceil((lines * columns) / 2);
  }

  const _random = (long = true) => {
    const _long =
      "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz`";
    const _short = "0123456789abcdefghijklmnopqrstuvwxyz";

    if (_long) {
      return _long[Math.floor(Math.random() * _long.length)];
    } else {
      return _short[Math.floor(Math.random() * _short.length)];
    }
  };

  const _refresh = () => {
    let stop = true,
      _current = "";

    const _update = (index, letter, opts = { long: false }) => {
      if (!current[index]) {
        stop = false;
        _current += _random(opts.long);
      } else if (current[index] !== letter) {
        stop = false;
        _current += _random(opts.long);
      } else {
        _current += current[index];
      }
    };

    for (let i = 0; i <= lines * columns; i++) {
      switch (i) {
        case middle:
          _update(i, "s", { long: true });
          break;
        case middle + 1:
          _update(i, "p", { long: true });
          break;
        case middle + 2:
          _update(i, "e", { long: true });
          break;
        case middle + 3:
          _update(i, "c", { long: true });
          break;
        case middle + 4:
          _update(i, "t", { long: true });
          break;
        case middle + 5:
          _update(i, "r", { long: true });
          break;
        case middle + 6:
          _update(i, "e", { long: true });
          break;
        default:
          _update(i, "`");
      }
    }

    current = _current;

    if (stop) {
      clearInterval(loop);
    }
  };

  const square = () => {
    loop = setInterval(_refresh, 8);

    return {
      destroy() {},
    };
  };
</script>

<style lang="scss">
  #square {
    color: $cyan;
    opacity: 0.4;
    height: 300px;
    width: 300px;
    position: absolute;
    top: -1 * $GU;
    left: 6 * $GU;
    overflow: hidden;
    word-wrap: break-word;
    user-select: none;
  }
</style>

<div
  transition:fade={{ duration: 2500 }}
  id="square"
  use:square
  style="height: {height}px; width: {width}px; font-size: {em}px; line-height: {em}px;"
>
  {current}
</div>

// src/Square.jsx
import React, { useEffect, useState, useRef } from "react"
import { css } from "@emotion/react"
import { GU, colors, fonts } from "./styles"
import { randChar, raf } from "./utils"

const CHARS_SHORT = "0123456789abcdefghijklmnopqrstuvwxyz"
const CHARS_LONG =
  "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

function createEmptyGrid(size) {
  return [...Array(size)].fill(" ")
}

// create the final grid
function createFinalGrid(size, placeholder, word, wordIndex) {
  return [...Array(size)].map(
    (_, index) => word[index - wordIndex] || placeholder
  )
}

// update the grid with random chars
function updateGrid(grid, finalGrid, placeholder, word, wordIndex) {
  return grid.map((char, index) => {
    if (finalGrid[index] === char) return char

    // the word is using the longer set of chars
    const isWord = index >= wordIndex && index < wordIndex + word.length
    return randChar(isWord ? CHARS_LONG + word : CHARS_SHORT + placeholder)
  })
}

// convert a grid to string + add line breaks
function gridToHtml(grid, columns) {
  return grid.reduce((html, char, index) => {
    return html + (index > 0 && index % columns === 0 ? "\n" : "") + char
  }, "")
}

function Square({
  word = "spectre",
  placeholder = "`",
  wordPosition = 0.5, // 0 to 1
  width = 18.5 * GU,
  height = 18.5 * GU,
  updateInterval = 1000 / 60, // ms
}) {
  const gridRef = useRef()
  const measureRef = useRef()

  useEffect(() => {
    const {
      width: charWidth,
      height: charHeight,
    } = measureRef.current.getBoundingClientRect()

    const columns = Math.ceil(width / charWidth)
    const lines = Math.ceil(height / charHeight)
    const wordIndex = Math.ceil(columns * lines * wordPosition)
    const finalGrid = createFinalGrid(
      lines * columns,
      placeholder,
      word,
      wordIndex
    )

    let gridHtml = ""
    let grid = createEmptyGrid(lines * columns)
    const finalGridHtml = gridToHtml(finalGrid, columns)

    const stop = raf(() => {
      if (gridHtml === finalGridHtml) {
        stop()
        return
      }

      grid = updateGrid(grid, finalGrid, placeholder, word, wordIndex)
      gridHtml = gridToHtml(grid, columns)
      if (gridRef.current) {
        gridRef.current.innerHTML = gridHtml
      }
    }, updateInterval)

    return stop
  }, [word, placeholder, wordPosition, width, height, updateInterval])

  return (
    <pre
      css={css`
        width: ${width}px;
        height: ${height}px;
        font-size: 12px;
        line-height: 12px;
        user-select: none;
        color: ${colors.cyan};
        opacity: 0.4;
      `}
    >
      <span
        ref={measureRef}
        css={css`
          position: absolute;
          opacity: 0;
        `}
      >
        m
      </span>
      <span ref={gridRef} />
    </pre>
  )
}

export default Square
